### ISSUE TITLE
User input when updating enum breaks

### ISSUE THREAD

**Issue by cjlucas** [cjlucas/archivedb#8]
`Traceback (most recent call last):
  File "bin/archivedb", line 17, in <module>
    if cmd == "start": archivedb.core.main()
  File "/Users/chris/Dropbox/code/github/archivedb/archivedb/core.py", line 110, in main
    _database_check()
  File "/Users/chris/Dropbox/code/github/archivedb/archivedb/core.py", line 60, in _database_check
    if input("Update? ").lower() in ('y', 'yes'):
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined`

This is because Python2 should use raw_input, which doesn't exist in Python3.

OS: OS X 10.7
Python: 2.7

**Comment by cjlucas** [comment]
Fixed, will be included in v0.2.2
